### ISSUE TITLE
Class "Darkterminal\TursoHTTP" not found

### ISSUE THREAD

**Issue by ashisbiswas** [darkterminal/turso-http#2]
I am using Codeigniter 4 and using composer I have installed it. Now when i open the page it shows "Class "Darkterminal\TursoHTTP" not found"

```
use Darkterminal\DataType;
use Darkterminal\SadQuery;
use Darkterminal\TursoHTTP;

class AdminController extends BaseController
{
      public function test(){
        $databaseName       = "dbtest";
        $organizationName   = "org";
        $token              = "12345";

        $tursoAPI = new TursoHTTP($databaseName, $organizationName, $token);
        $query    = new SadQuery();
    }

}
```

**Comment by darkterminal** [comment]
Hi @ashisbiswas, you can try to import using `use Darkterminal\TursoHttp\TursoHTTP`. Btw, this is version will deprecated until next release. Cz I made completely BREAKING CHANGES for Turso Remote HTTP Connection.
